# Probe owners supply facts; Cargo and standalone CMake share the policy.
if(NOT DEFINED ACPP_TARGETS OR ACPP_TARGETS STREQUAL "")
    set(_vendors 0)
    foreach(_vendor NVIDIA AMD INTEL)
        if(X2_HAVE_${_vendor})
            math(EXPR _vendors "${_vendors} + 1")
        endif()
    endforeach()
    if(WIN32)
        set(ACPP_TARGETS "generic;omp")
    elseif(_vendors GREATER 1 OR X2_HAVE_NVIDIA OR NOT X2_AMD_GFX)
        set(ACPP_TARGETS generic)
    elseif(X2_AMD_GFX MATCHES "^gfx101[012]$")
        if(NOT "$ENV{XCHPLOT2_FORCE_GFX_SPOOF}" STREQUAL "" AND
           NOT "$ENV{XCHPLOT2_FORCE_GFX_SPOOF}" STREQUAL "0")
            set(ACPP_TARGETS "hip:gfx1013")
            message(WARNING "xchplot2: RDNA1 legacy gfx1013 spoof requested; unset XCHPLOT2_FORCE_GFX_SPOOF if kernels produce no output")
        elseif(NOT "$ENV{XCHPLOT2_NO_GFX_SPOOF}" STREQUAL "" AND
               NOT "$ENV{XCHPLOT2_NO_GFX_SPOOF}" STREQUAL "0")
            set(ACPP_TARGETS "hip:${X2_AMD_GFX}")
            message(WARNING "xchplot2: native RDNA1 AOT requested; unset XCHPLOT2_NO_GFX_SPOOF if AdaptiveCpp cannot compile this target")
        else()
            set(ACPP_TARGETS generic)
            message(STATUS "xchplot2: RDNA1 ${X2_AMD_GFX}: using generic SSCP; legacy AOT overrides remain available")
        endif()
    else()
        set(ACPP_TARGETS "hip:${X2_AMD_GFX}")
    endif()
endif()
if(NOT DEFINED XCHPLOT2_BUILD_CUDA OR XCHPLOT2_BUILD_CUDA STREQUAL "")
    if(X2_HAVE_NVIDIA)
        set(XCHPLOT2_BUILD_CUDA ON)
    elseif(X2_HAVE_AMD OR X2_HAVE_INTEL)
        set(XCHPLOT2_BUILD_CUDA OFF)
    elseif(X2_HAVE_NVCC)
        set(XCHPLOT2_BUILD_CUDA ON)
    else()
        set(XCHPLOT2_BUILD_CUDA OFF)
    endif()
endif()
# Cargo's runtime link decisions use canonical ON/OFF values too.
if(XCHPLOT2_BUILD_CUDA)
    set(XCHPLOT2_BUILD_CUDA ON)
else()
    set(XCHPLOT2_BUILD_CUDA OFF)
endif()
if(X2_SELECTION_OUTPUT)
    file(WRITE "${X2_SELECTION_OUTPUT}" "${ACPP_TARGETS}\n${XCHPLOT2_BUILD_CUDA}\n")
endif()
